# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_ranking', models.IntegerField()),
                ('playoffs', models.CharField(max_length=255)),
                ('record', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('size', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AreaCrime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('total_enrollment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TestScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.School')),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='testscores',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.TestType'),
        ),
        migrations.AddField(
            model_name='funding',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.School'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.School'),
        ),
        migrations.AddField(
            model_name='areacrime',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.School'),
        ),
        migrations.AddField(
            model_name='activities',
            name='acivity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.ActivityType'),
        ),
        migrations.AddField(
            model_name='activities',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.School'),
        ),
    ]
