# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20170316_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testscores',
            old_name='score',
            new_name='below',
        ),
        migrations.AddField(
            model_name='testscores',
            name='exceeding',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testscores',
            name='meeting',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
