# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20170316_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
