# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20170316_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frlunch', models.CharField(max_length=225)),
                ('gifted', models.CharField(max_length=225)),
                ('specialed', models.CharField(max_length=225)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.School')),
            ],
        ),
        migrations.CreateModel(
            name='StatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='statistics',
            name='stat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.StatType'),
        ),
    ]
